spring.application.name=mscartelera

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Limita las conexiones simultáneas para ahorrar recursos
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1